export const COURSES_FETCH = 'COURSES_FETCH';
export const COURSES_FETCH_OK = 'COURSES_FETCH_OK';
export const COURSES_FETCH_FAIL = 'COURSES_FETCH_FAIL';

export const COURSES_ENROLL = 'COURSES_ENROLL';
export const COURSES_ENROLL_OK = 'COURSES_ENROLL_OK';
export const COURSES_ENROLL_FAIL = 'COURSES_ENROLL_FAIL';
