export const COURSES_FETCH = 'COURSES_FETCH';
export const COURSES_FETCH_OK = 'COURSES_FETCH_OK';
export const COURSES_FETCH_FAIL = 'COURSES_FETCH_FAIL';

export const COURSES_ENROLL = 'COURSES_ENROLL';
export const COURSES_ENROLL_OK = 'COURSES_ENROLL_OK';
export const COURSES_ENROLL_FAIL = 'COURSES_ENROLL_FAIL';

export enum COURSE {
    ASSIGN_MENTORS = 'COURSE_ASSIGN_MENTORS',
    ASSIGN_MENTORS_OK = 'COURSE_ASSIGN_MENTORS_OK',
    ASSIGN_MENTORS_FAIL = 'COURSE_ASSIGN_MENTORS_FAIL',
}
