export enum COURSE {
    FETCH_ALL_COURSES = 'COURSE_FETCH_ALL_COURSES',
    FETCH_ALL_COURSES_OK = 'COURSE_FETCH_ALL_COURSES_OK',
    FETCH_ALL_COURSES_FAIL = 'COURSE_FETCH_ALL_COURSES_FAIL',

    ENROLL = 'COURSE_ENROLL',
    ENROLL_OK = 'COURSE_ENROLL_OK',
    ENROLL_FAIL = 'COURSE_ENROLL_FAIL',

    ASSIGN_MENTORS = 'COURSE_ASSIGN_MENTORS',
    ASSIGN_MENTORS_OK = 'COURSE_ASSIGN_MENTORS_OK',
    ASSIGN_MENTORS_FAIL = 'COURSE_ASSIGN_MENTORS_FAIL',

    FETCH_STUDENTS = 'COURSE_FETCH_STUDENTS',
    FETCH_STUDENTS_OK = 'COURSE_FETCH_STUDENTS_OK',
    FETCH_STUDENTS_FAIL = 'COURSE_FETCH_STUDENTS_FAIL',

    FETCH_MENTORS = 'COURSE_FETCH_MENTORS',
    FETCH_MENTORS_OK = 'COURSE_FETCH_MENTORS_OK',
    FETCH_MENTORS_FAIL = 'COURSE_FETCH_MENTORS_FAIL',
}
