export enum EVENTS {
    FETCH_COURSE_EVENTS = 'EVENTS_FETCH_COURSE_EVENTS',
    FETCH_COURSE_EVENTS_OK = 'EVENTS_FETCH_COURSE_EVENTS_OK',
    FETCH_COURSE_EVENTS_FAIL = 'EVENTS_FETCH_COURSE_EVENTS_FAIL',
}
