export enum EVENTS {
    FETCH_COURSE_EVENTS_AND_STAGES = 'EVENTS_FETCH_COURSE_EVENTS_AND_STAGES',
    FETCH_COURSE_EVENTS_AND_STAGES_OK = 'EVENTS_FETCH_COURSE_EVENTS_AND_STAGES_OK',
    FETCH_COURSE_EVENTS_AND_STAGES_FAIL = 'EVENTS_FETCH_COURSE_EVENTS_AND_STAGES_FAIL',
}
