export const PROFILE_UPDATE = 'PROFILE_STUDENT_UPDATE';
export const PROFILE_UPDATE_OK = 'PROFILE_STUDENT_UPDATE_OK';
export const PROFILE_UPDATE_FAIL = 'PROFILE_STUDENT_UPDATE_FAIL';

export const PROFILE_FETCH = 'PROFILE_STUDENT_FETCH';
export const PROFILE_FETCH_OK = 'PROFILE_STUDENT_FETCH_OK';
export const PROFILE_FETCH_FAIL = 'PROFILE_STUDENT_FETCH_FAIL';
