export enum SCHEDULE {
    FETCH_COURSE_EVENTS_AND_STAGES = 'SCHEDULE_FETCH_COURSE_EVENTS_AND_STAGES',
    FETCH_COURSE_EVENTS_AND_STAGES_OK = 'SCHEDULE_FETCH_COURSE_EVENTS_AND_STAGES_OK',
    FETCH_COURSE_EVENTS_AND_STAGES_FAIL = 'SCHEDULE_FETCH_COURSE_EVENTS_AND_STAGES_FAIL',
    ADD_COURSE_STAGE = 'SCHEDULE_ADD_COURSE_STAGE',
    ADD_COURSE_STAGE_OK = 'SCHEDULE_ADD_COURSE_STAGE_OK',
    ADD_COURSE_STAGE_FAIL = 'SCHEDULE_ADD_COURSE_STAGE_FAIL',
    UPDATE_COURSE_STAGE = 'SCHEDULE_UPDATE_COURSE_STAGE',
    UPDATE_COURSE_STAGE_OK = 'SCHEDULE_UPDATE_COURSE_STAGE_OK',
    UPDATE_COURSE_STAGE_FAIL = 'SCHEDULE_UPDATE_COURSE_STAGE_FAIL',
}
