export enum SCHEDULE {
    FETCH_COURSE_EVENTS_AND_STAGES = 'SCHEDULE_FETCH_COURSE_EVENTS_AND_STAGES',
    FETCH_COURSE_EVENTS_AND_STAGES_OK = 'SCHEDULE_FETCH_COURSE_EVENTS_AND_STAGES_OK',
    FETCH_COURSE_EVENTS_AND_STAGES_FAIL = 'SCHEDULE_FETCH_COURSE_EVENTS_AND_STAGES_FAIL',
    ADD_COURSE_STAGE = 'SCHEDULE_ADD_COURSE_STAGE',
    ADD_COURSE_STAGE_OK = 'SCHEDULE_ADD_COURSE_STAGE_OK',
    ADD_COURSE_STAGE_FAIL = 'SCHEDULE_ADD_COURSE_STAGE_FAIL',
    UPDATE_COURSE_STAGE = 'SCHEDULE_UPDATE_COURSE_STAGE',
    UPDATE_COURSE_STAGE_OK = 'SCHEDULE_UPDATE_COURSE_STAGE_OK',
    UPDATE_COURSE_STAGE_FAIL = 'SCHEDULE_UPDATE_COURSE_STAGE_FAIL',
    DELETE_COURSE_STAGE = 'SCHEDULE_DELETE_COURSE_STAGE',
    DELETE_COURSE_STAGE_OK = 'SCHEDULE_DELETE_COURSE_STAGE_OK',
    DELETE_COURSE_STAGE_FAIL = 'SCHEDULE_DELETE_COURSE_STAGE_FAIL',
}

export const INPUT_DATE_FORMAT = 'YYYY-MM-DD';
export const INPUT_DATE_TIME_FORMAT = 'YYYY-MM-DDTHH:mm';
export const DATE_FORMAT = 'DD.MM.YYYY';

export const DELETE_STAGE_CONTEXT = {
    title: 'Delete a Stage?',
    body: 'Do you really want to delete this stage?',
    isError: false,
};

export const DELETE_STAGE_ERROR_CONTEXT = {
    title: 'Error',
    body: 'This Stage cannot be deleted because it is not empty.',
    isError: true,
};
