export enum SCHEDULE {
    FETCH_COURSE_EVENTS_AND_STAGES = 'SCHEDULE_FETCH_COURSE_EVENTS_AND_STAGES',
    FETCH_COURSE_EVENTS_AND_STAGES_OK = 'SCHEDULE_FETCH_COURSE_EVENTS_AND_STAGES_OK',
    FETCH_COURSE_EVENTS_AND_STAGES_FAIL = 'SCHEDULE_FETCH_COURSE_EVENTS_AND_STAGES_FAIL',
}
