export enum USER {
    PARTICIPATIONS_FETCH = 'USER_PARTICATIONS_FETCH',
    PARTICIPATIONS_FETCH_OK = 'USER_PARTICATIONS_FETCH_OK',
    PARTICIPATIONS_FETCH_FAIL = 'USER_PARTICATIONS_FETCH_FAIL',

    PROFILE_FETCH = 'USER_PROFILE_FETCH',
    PROFILE_FETCH_OK = 'USER_PROFILE_FETCH_OK',
    PROFILE_FETCH_FAIL = 'USER_PROFILE_FETCH_FAIL',

    PROFILE_UPDATE = 'USER_PROFILE_UPDATE',
    PROFILE_UPDATE_OK = 'USER_PROFILE_UPDATE_OK',
    PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL',

    FEED_FETCH = 'USER_FEED_FETCH',
    FEED_FETCH_OK = 'USER_FEED_FETCH_OK',
    FEED_FETCH_FAIL = 'USER_FEED_FETCH_FAIL',
}
